apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-flask-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-flask-app.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      containers:
        - name: flask-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
      securityContext:
        fsGroup: 1000
