#  CD Flow - hello-flask-app Deployment to 2bcloud EKS 
name: CD Flow Deployment hello-flask-app to EKS 
on:
  # uncomment the following sectin in case you want automatically deployment after CI workflow
   # workflow_run:
   #  workflows: ["CI Flow Create Docker image"]  # Name of the CI workflow
   #  types:
   #    - completed  # Trigger CD when CI completes
      
   workflow_dispatch:
    inputs:
      image_tag:
        description: "Commit SHA (image tag) from 'CI Develeap Pipeline with Docker'  :"
        required: true
        default: ""
        
env:
  AWS_ACCESS_KEY_ID      : ${{ secrets.VI_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY  : ${{ secrets.VI_AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION     : "eu-north-1"
  AWS_REGION_NAME        : "eu-north-1"
  EKS_NAME               : "vi-eks-cluster"
  APP_NAME               : "hello-flask-app"
   
jobs:
  
  build:
    
    name: Deployment
    runs-on: ubuntu-latest
    steps:

    - name: Check for Commit SHA input
      id: check_sha
      run: |
        if [ -z "${{ github.event.inputs.image_tag }}" ]; then
          echo "Error: Commit SHA (image_tag)is required as input!, please take it from CI workflow"  # Fail the job if no input is provided
          exit 1
        fi

        echo "Using Commit SHA: ${{ github.event.inputs.image_tag }}"

    # Set Short Commit git Commit SHA
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2
          
    
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    :  ${{ secrets.VI_AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.VI_AWS_SECRET_KEY }}
        aws-region           :  ${{ env.AWS_REGION_NAME }}

      
    # For AWS ECR login 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'
 
   
    # Update .kube/config file with cluster details
    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_NAME --region $AWS_REGION
      
    # Create Namespace if it doesn't exist and delete old deployment
    - name: Create Namespace if it doesn't exist
      run: |
        kubectl get namespace $APP_NAME || kubectl create namespace $APP_NAME
        kubectl delete deployment $APP_NAME -n $APP_NAME --ignore-not-found

    # Update Image tag in values file
    - name: Update values.yaml with real Image 
      env:
        IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        REPO     : ${{ secrets.BCLOUD_AWS_ECR_REGISTRY }}
      run: |
         sed -i "s|latest|$IMAGE_TAG|g" helm-charts/$APP_NAME/values.yaml
         sed -i "s|2bcloudrepository|$REPO|g" helm-charts/$APP_NAME/values.yaml
         

   # Validate the Helm chart before deployment
    - name: Validate Helm chart (lint)
      run: |
        helm lint ./helm-charts/$APP_NAME
        
    # Deploy hello-flask-app helm chart
    - name: Deploy helm chart
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade --install $APP_NAME helm-charts/$APP_NAME/ --cleanup-on-fail --namespace $APP_NAME --wait

    - name: Wait for service external IP
      id: wait-for-service
      run: |
        echo "Waiting for external IP..."
        for i in {1..20}; do
          EXTERNAL_IP=$(kubectl get svc hello-flask-app -n hello-flask-app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [[ -n "$EXTERNAL_IP" ]]; then
            echo "Found IP: $EXTERNAL_IP"
            echo "external_ip=$EXTERNAL_IP" >> $GITHUB_OUTPUT
            break
          fi
          echo "Still waiting..."
          sleep 15
        done
        if [[ -z "$EXTERNAL_IP" ]]; then
          echo "Timed out waiting for service external IP"
          exit 1
        fi

    - name: Check health endpoint
      run: |
        echo "Checking /healthz on http://${{ steps.wait-for-service.outputs.external_ip }}:5000"
        for i in {1..10}; do
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${{ steps.wait-for-service.outputs.external_ip }}:5000/healthz || true)
          echo "Health check status: $STATUS"
          if [[ "$STATUS" == "200" ]]; then
            echo "App is healthy!"
            exit 0
          fi
          sleep 10
        done
        echo "App failed health check!"
        exit 1

    - name: Print Success Message for Deploy hello-flask-app
      run : echo "Deployment hello-flask-app to 2bcloud EKS with helm   FINISHED SUCCESSFULLY!"
      
